project_id = "pvbjsztremgynwsjokge"

[functions.telegram-auth]
verify_jwt = false

[functions.generate-text]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.evaluate-prompt]
verify_jwt = false