// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvbjsztremgynwsjokge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2YmpzenRyZW1neW53c2pva2dlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODc2NjgsImV4cCI6MjA3MTM2MzY2OH0.z8CaFCQr6OLdsb1JTU9WVi-8UQ6MPnsWRFJTjSOik54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});